import { JSONSchema7 } from 'json-schema'

export const BLOCKCHAIN_INPUTS: Record<string, JSONSchema7> = {
  network: {
    title: 'Network',
    type: 'integer',
    oneOf: [
      { title: 'Ethereum', const: 1 },
      { title: 'Arbitrum', const: 42161 },
      { title: 'Avalanche', const: 43114 },
      { title: 'BNB Chain (BSC)', const: 56 },
      { title: 'Celo', const: 42220 },
      { title: 'Cronos', const: 25 },
      { title: 'Fantom', const: 250 },
      { title: 'Gnosis', const: 100 },
      { title: 'Görli', const: 5 },
      { title: 'Harmony', const: 1666600000 },
      { title: 'Kovan', const: 42 },
      { title: 'Metis', const: 1088 },
      { title: 'Optimism', const: 10 },
      { title: 'Polygon', const: 137 },
      { title: 'Rinkeby', const: 4 },
      { title: 'Ropsten', const: 3 },
      { title: 'Sepolia', const: 11155111 },
      { title: 'Tomb Chain', const: 6969 },
    ],
  },
  covalent_networks: {
    title: 'Network',
    type: 'integer',
    oneOf: [
      { title: 'Ethereum', const: 1 },
      { title: 'Arbitrum', const: 42161 },
      { title: 'Astar', const: 592 },
      { title: 'Aurora', const: 1313161554 },
      { title: 'Axie/Ronin', const: 2020 },
      { title: 'Avalanche', const: 43114 },
      { title: 'BNB Chain (BSC)', const: 56 },
      { title: 'Cronos', const: 25 },
      { title: 'Evmos', const: 9001 },
      { title: 'Fantom', const: 250 },
      { title: 'Görli', const: 5 },
      { title: 'Harmony', const: 1666600000 },
      { title: 'IoTeX', const: 4689 },
      { title: 'Metis', const: 1088 },
      { title: 'Moonbeam', const: 1284 },
      { title: 'Moonriver', const: 1285 },
      { title: 'Mumbai Testnet', const: 80001 },
      { title: 'Optimism', const: 10 },
      { title: 'Palm', const: 11297108109 },
      { title: 'Polygon', const: 137 },
      { title: 'RSK', const: 30 },
      { title: 'Solana', const: 1399811149 },
    ],
  },
  address: {
    title: 'Contract Address',
    type: 'string',
  },
}
